[Appearance]
style=Fusion
icon_theme=Papirus-Dark
color_scheme_path=/usr/share/qt6ct/colors/darker.conf
custom_palette=true

[Colors:Active]
windowBackground=#1e2030
windowText=#e0e2f0
base=#151621
text=#e0e2f0
button=#26283a
buttonText=#e0e2f0
highlight=#4fd6ff
highlightedText=#151621
link=#4fd6ff
linkVisited=#cdb7ff
alternateBase=#1e2030
toolTipBase=#1e2030
toolTipText=#e0e2f0
shadow=#0a0a0a
light=#3d4058
midlight=#2a2c3c
mid=#1e2030
dark=#151621
window=#151621

[Colors:Disabled]
windowBackground=#1e2030
windowText=#8a8a9a
base=#151621
text=#8a8a9a
button=#26283a
buttonText=#5c5c6c
highlight=#2a2c3c
highlightedText=#8a8a9a
link=#8a8a9a
linkVisited=#5c5c6c
alternateBase=#1e2030
toolTipBase=#1e2030
toolTipText=#8a8a9a
shadow=#0a0a0a
light=#2a2c3c
midlight=#26283a
mid=#1e2030
dark=#151621
window=#151621

[Colors:Inactive]
windowBackground=#1e2030
windowText=#8a8a9a
base=#151621
text=#8a8a9a
button=#26283a
buttonText=#8a8a9a
highlight=#2a2c3c
highlightedText=#8a8a9a
link=#4fd6ff
linkVisited=#cdb7ff
alternateBase=#1e2030
toolTipBase=#1e2030
toolTipText=#8a8a9a
shadow=#0a0a0a
light=#2a2c3c
midlight=#26283a
mid=#1e2030
dark=#151621
window=#151621

[Fonts]
general=JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0,0,0,0,0,0,1
fixed=JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0,0,0,0,0,0,1

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=0
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_access_key=true
wheel_scroll_lines=3

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\a\x80\0\0\0\0\0\0\x5\x3\0\0\x3\x89\0\0\a\xb0\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\x5\x3\0\0\x3\x89\0\0\a\xb0\0\0\0\0\0\0\0\0)

[Troubleshooting]
force_raster_widgets=false
ignored_app_list=@Invalid()
