general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
}

auth {
    pam = true
    module = "hyprlock"
    fingerprint:enabled = true
}

background {
    color = rgb(2D2D2D)
}

input-field {
    size = 420, 56
    outline_thickness = 2
    rounding = 0
    dots_center = true
    fade_on_empty = false
    placeholder_text = ENTER PASSWORD
    text_color = rgb(F2E9E9)
    font_color = rgb(F2E9E9)
    outer_color = rgb(46658C)
    inner_color = rgb(2D2D2D)
    check_color = rgb(6D8C9D)
    fail_color = rgb(E63946)
    position = 0, -80
    halign = center
    valign = center
}

label {
    text = PIXEL RICE LOCK
    color = rgb(D9895B)
    font_size = 24
    font_family = Terminus
    position = 0, 40
    halign = center
    valign = center
}